authors:
  felix:
    name: Félix Poullet-Pagès
    description: Co-fondateur
    avatar: https://avatars.githubusercontent.com/u/70573684
  jw:
    name: Jean Wilfrid Poullet
    description: Co-fondateur
    avatar: https://fr.gravatar.com/images/homepage/avatar-04.png
  cat:
    name: Catherine Pagès
    description: Membre
    avatar: https://fr.gravatar.com/images/homepage/avatar-06.png