site_url: https://soleildepomme.asso.eu.org
search: false
media_folder: "docs/assets"
public_folder: "docs/assets"
backend:
  name: github
  branch: main
  repo: "felix-commits/soleil-de-pomme"
+  base_url: https://account.soleildepomme.asso.eu.org